# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\"\x18\n\x05Hello\x12\x0f\n\x07message\x18\x01 \x01(\t2\"\n\x04\x45\x63ho\x12\x1a\n\x08SayHello\x12\x06.Hello\x1a\x06.Hellob\x06proto3')



_HELLO = DESCRIPTOR.message_types_by_name['Hello']
Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), {
  'DESCRIPTOR' : _HELLO,
  '__module__' : 'hello_pb2'
  # @@protoc_insertion_point(class_scope:Hello)
  })
_sym_db.RegisterMessage(Hello)

_ECHO = DESCRIPTOR.services_by_name['Echo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLO._serialized_start=15
  _HELLO._serialized_end=39
  _ECHO._serialized_start=41
  _ECHO._serialized_end=75
# @@protoc_insertion_point(module_scope)
